"use strict";(()=>{var e={};e.id=3703,e.ids=[3703],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},73786:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>y,requestAsyncStorage:()=>d,routeModule:()=>p,serverHooks:()=>h,staticGenerationAsyncStorage:()=>m});var o={};r.r(o),r.d(o,{GET:()=>f});var n=r(49303),a=r(88716),s=r(60670),i=r(55661);let l=["/admin","/admin/","/api/","/aulas","/aulas/","/bookings","/bookings/","/configuracoes","/mensagens","/mensagens/","/tutor/dashboard","/tutor/onboarding","/tutor/settings"];var u=r(25322),c=r(60707);async function f(){var e;let t=await (e=(0,u.zL)(),{rules:{userAgent:"*",allow:"/",disallow:[...l]},sitemap:`${e}/sitemap.xml`}),r=(0,c.resolveRouteData)(t,"robots");return new i.NextResponse(r,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let p=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2Fworkspace%2Fapp%2Frobots.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:o}),{requestAsyncStorage:d,staticGenerationAsyncStorage:m,serverHooks:h}=p,g="/robots.txt/route";function y(){return(0,s.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:m})}},25322:(e,t,r)=>{r.d(t,{zL:()=>o});function o(e=process.env){return(function(e=process.env){for(let t of[e.NEXT_PUBLIC_SITE_URL,e.VERCEL_URL?`https://${e.VERCEL_URL}`:void 0]){let e=function(e){let t=e?.trim();if(t)try{let e=/^[a-zA-Z][a-zA-Z\d+.-]*:/.test(t)?t:`https://${t}`,r=new URL(e);return"localhost"===r.hostname||r.hostname,r}catch{return}}(t);if(e)return e}return new URL("production"===e.NODE_ENV?"https://www.aprendizbay.com.br":"http://localhost:3000")})(e).origin.replace(/\/$/,"")}},60707:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return s},resolveRobots:function(){return n},resolveRouteData:function(){return i},resolveSitemap:function(){return a}});let o=r(91389);function n(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,o.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,o.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,o.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,o.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function a(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let n of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var o;r+=`<url>
<loc>${n.url}</loc>
`;let e=null==(o=n.alternates)?void 0:o.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(n.lastModified){let e=n.lastModified instanceof Date?n.lastModified.toISOString():n.lastModified;r+=`<lastmod>${e}</lastmod>
`}n.changeFrequency&&(r+=`<changefreq>${n.changeFrequency}</changefreq>
`),"number"==typeof n.priority&&(r+=`<priority>${n.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function s(e){return JSON.stringify(e)}function i(e,t){return"robots"===t?n(e):"sitemap"===t?a(e):"manifest"===t?s(e):""}},91389:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function o(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return o}})}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[8948,2518],()=>r(73786));module.exports=o})();