"use strict";(()=>{var e={};e.id=3703,e.ids=[3703],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},14635:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>h,patchFetch:()=>g,requestAsyncStorage:()=>p,routeModule:()=>c,serverHooks:()=>m,staticGenerationAsyncStorage:()=>d});var o={};r.r(o),r.d(o,{GET:()=>f});var n=r(49303),a=r(88716),s=r(60670),i=r(55661),l=r(25322),u=r(60707);async function f(){let e=await function(){let e=(0,l.z)();return{rules:{userAgent:"*",allow:"/",disallow:["/admin","/api/","/bookings","/mensagens","/tutor/dashboard","/tutor/onboarding","/tutor/settings"]},sitemap:`${e}/sitemap.xml`}}(),t=(0,u.resolveRouteData)(e,"robots");return new i.NextResponse(t,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let c=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2Fworkspace%2Fapp%2Frobots.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:o}),{requestAsyncStorage:p,staticGenerationAsyncStorage:d,serverHooks:m}=c,h="/robots.txt/route";function g(){return(0,s.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:d})}},25322:(e,t,r)=>{r.d(t,{z:()=>o});function o(){return(function(){for(let e of[process.env.NEXT_PUBLIC_SITE_URL,process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:void 0]){let t=function(e){let t=e?.trim();if(t)try{let e=/^[a-zA-Z][a-zA-Z\d+.-]*:/.test(t)?t:`https://${t}`;return new URL(e)}catch{return}}(e);if(t)return t}return new URL("http://localhost:3000")})().origin.replace(/\/$/,"")}},60707:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return s},resolveRobots:function(){return n},resolveRouteData:function(){return i},resolveSitemap:function(){return a}});let o=r(91389);function n(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,o.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,o.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,o.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,o.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function a(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let n of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var o;r+=`<url>
<loc>${n.url}</loc>
`;let e=null==(o=n.alternates)?void 0:o.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(n.lastModified){let e=n.lastModified instanceof Date?n.lastModified.toISOString():n.lastModified;r+=`<lastmod>${e}</lastmod>
`}n.changeFrequency&&(r+=`<changefreq>${n.changeFrequency}</changefreq>
`),"number"==typeof n.priority&&(r+=`<priority>${n.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function s(e){return JSON.stringify(e)}function i(e,t){return"robots"===t?n(e):"sitemap"===t?a(e):"manifest"===t?s(e):""}},91389:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function o(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return o}})}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[8948,2518],()=>r(14635));module.exports=o})();